export default [
  {
  login: "getify",
  id: 150330,
  node_id: "MDQ6VXNlcjE1MDMzMA==",
  avatar_url: "https://avatars.githubusercontent.com/u/150330?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/getify",
  html_url: "https://github.com/getify",
  followers_url: "https://api.github.com/users/getify/followers",
  following_url: "https://api.github.com/users/getify/following{/other_user}",
  gists_url: "https://api.github.com/users/getify/gists{/gist_id}",
  starred_url: "https://api.github.com/users/getify/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/getify/subscriptions",
  organizations_url: "https://api.github.com/users/getify/orgs",
  repos_url: "https://api.github.com/users/getify/repos",
  events_url: "https://api.github.com/users/getify/events{/privacy}",
  received_events_url: "https://api.github.com/users/getify/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "wesbos",
  id: 176013,
  node_id: "MDQ6VXNlcjE3NjAxMw==",
  avatar_url: "https://avatars.githubusercontent.com/u/176013?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/wesbos",
  html_url: "https://github.com/wesbos",
  followers_url: "https://api.github.com/users/wesbos/followers",
  following_url: "https://api.github.com/users/wesbos/following{/other_user}",
  gists_url: "https://api.github.com/users/wesbos/gists{/gist_id}",
  starred_url: "https://api.github.com/users/wesbos/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/wesbos/subscriptions",
  organizations_url: "https://api.github.com/users/wesbos/orgs",
  repos_url: "https://api.github.com/users/wesbos/repos",
  events_url: "https://api.github.com/users/wesbos/events{/privacy}",
  received_events_url: "https://api.github.com/users/wesbos/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "taylorotwell",
  id: 463230,
  node_id: "MDQ6VXNlcjQ2MzIzMA==",
  avatar_url: "https://avatars.githubusercontent.com/u/463230?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/taylorotwell",
  html_url: "https://github.com/taylorotwell",
  followers_url: "https://api.github.com/users/taylorotwell/followers",
  following_url: "https://api.github.com/users/taylorotwell/following{/other_user}",
  gists_url: "https://api.github.com/users/taylorotwell/gists{/gist_id}",
  starred_url: "https://api.github.com/users/taylorotwell/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/taylorotwell/subscriptions",
  organizations_url: "https://api.github.com/users/taylorotwell/orgs",
  repos_url: "https://api.github.com/users/taylorotwell/repos",
  events_url: "https://api.github.com/users/taylorotwell/events{/privacy}",
  received_events_url: "https://api.github.com/users/taylorotwell/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "sokra",
  id: 1365881,
  node_id: "MDQ6VXNlcjEzNjU4ODE=",
  avatar_url: "https://avatars.githubusercontent.com/u/1365881?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/sokra",
  html_url: "https://github.com/sokra",
  followers_url: "https://api.github.com/users/sokra/followers",
  following_url: "https://api.github.com/users/sokra/following{/other_user}",
  gists_url: "https://api.github.com/users/sokra/gists{/gist_id}",
  starred_url: "https://api.github.com/users/sokra/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/sokra/subscriptions",
  organizations_url: "https://api.github.com/users/sokra/orgs",
  repos_url: "https://api.github.com/users/sokra/repos",
  events_url: "https://api.github.com/users/sokra/events{/privacy}",
  received_events_url: "https://api.github.com/users/sokra/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "toddmotto",
  id: 1655968,
  node_id: "MDQ6VXNlcjE2NTU5Njg=",
  avatar_url: "https://avatars.githubusercontent.com/u/1655968?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/toddmotto",
  html_url: "https://github.com/toddmotto",
  followers_url: "https://api.github.com/users/toddmotto/followers",
  following_url: "https://api.github.com/users/toddmotto/following{/other_user}",
  gists_url: "https://api.github.com/users/toddmotto/gists{/gist_id}",
  starred_url: "https://api.github.com/users/toddmotto/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/toddmotto/subscriptions",
  organizations_url: "https://api.github.com/users/toddmotto/orgs",
  repos_url: "https://api.github.com/users/toddmotto/repos",
  events_url: "https://api.github.com/users/toddmotto/events{/privacy}",
  received_events_url: "https://api.github.com/users/toddmotto/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "Alaev",
  id: 3925474,
  node_id: "MDQ6VXNlcjM5MjU0NzQ=",
  avatar_url: "https://avatars.githubusercontent.com/u/3925474?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Alaev",
  html_url: "https://github.com/Alaev",
  followers_url: "https://api.github.com/users/Alaev/followers",
  following_url: "https://api.github.com/users/Alaev/following{/other_user}",
  gists_url: "https://api.github.com/users/Alaev/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Alaev/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Alaev/subscriptions",
  organizations_url: "https://api.github.com/users/Alaev/orgs",
  repos_url: "https://api.github.com/users/Alaev/repos",
  events_url: "https://api.github.com/users/Alaev/events{/privacy}",
  received_events_url: "https://api.github.com/users/Alaev/received_events",
  type: "User",
  site_admin: false
  }
  ]